// Generated by `npx next-push init`. Customize freely.
// This file is standalone (no imports) and handles all Web Push lifecycle events.

self.addEventListener("push", (event) => {
  let payload = null;
  try {
    payload = event.data ? event.data.json() : null;
  } catch {
    payload = { title: event.data?.text() ?? "Notification" };
  }
  const title = payload?.title ?? "Notification";
  event.waitUntil(
    self.registration.showNotification(title, {
      body: payload?.body,
      icon: payload?.icon ?? self.__NEXT_PUSH_DEFAULT_ICON__,
      badge: payload?.badge ?? self.__NEXT_PUSH_DEFAULT_BADGE__,
      image: payload?.image,
      tag: payload?.tag,
      data: { url: payload?.url ?? "/", raw: payload?.data },
      actions: payload?.actions,
    }),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = event.notification.data?.url ?? "/";
  event.waitUntil(
    (async () => {
      const absolute = new URL(url, self.location.origin).toString();
      const wcs = await self.clients.matchAll({
        type: "window",
        includeUncontrolled: true,
      });
      for (const c of wcs) {
        if (c.url === absolute) return c.focus();
      }
      return self.clients.openWindow(url);
    })(),
  );
});

self.addEventListener("pushsubscriptionchange", (event) => {
  event.waitUntil(
    (async () => {
      const vapidPub = self.__NEXT_PUSH_VAPID_PUBLIC_KEY__;
      const apiPath = self.__NEXT_PUSH_API_PATH__ ?? "/api/push";
      if (!vapidPub) return;
      const raw = atob(vapidPub.replace(/-/g, "+").replace(/_/g, "/"));
      const key = new Uint8Array(raw.length);
      for (let i = 0; i < raw.length; i++) key[i] = raw.charCodeAt(i);
      const newSub = await self.registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: key,
      });
      await fetch(apiPath, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(newSub.toJSON()),
      });
    })(),
  );
});
